const colors = {
  red: [
    'lightsalmon',
    'salmon',
    'darksalmon',
    'lightcoral',
    'indianred',
    'crimson',
    'firebrick',
    'red',
    'darkred',
  ],
  orange: [
    'coral',
    'tomato',
    'orangered',
    'gold',
    'orange',
    'darkorange',
    'indianred',
    'darksalmon',
    'red',
  ],
  yellow: [
    'yellow',
    'lemonchiffon',
    'lightgoldenrodyellow',
    'papayawhip',
    'moccasin',
    'peachpuff',
    'palegoldenrod',
    'darkkhaki',
    'red',
  ],
  green: [
    'lawngreen',
    'limegreen',
    'lime',
    'forestgreen',
    'darkgreen',
    'greenyellow',
    'yellowgreen',
    'springgreen',
    'olivedrab',
  ],
  cyan: [
    'cyan',
    'aquamarine',
    'lightcyan',
    'mediumaquamarine',
    'turquoise',
    'lightseagreen',
    'cadetblue',
    'darkcyan',
    'paleturquoise',
  ],
  blue: [
    'lightblue',
    'skyblue',
    'deepskyblue',
    'lightsteelblue',
    'dodgerblue',
    'steelblue',
    'midnightblue',
    'mediumblue',
    'royalblue',
  ],
};

export default colors;
